### PR TITLE
ArrayConverterTest#testCompletions() fails on Windows

### LINKED ISSUE #88: ArrayConverterTest#testCompletions() fails on Windows
Uses Unix style file separator in file path constants.

### PR DESCRIPTION
**Pull request by adityakishore**
This closes #88

### CODE REVIEW

**Comment by adityakishore** [comment]
With this commit, the failing test passes on Windows/Mac/Linux.

**Comment by ericbottard** [comment]
Thanks for this contribution. Before it can be merged, can you please confirm you have signed our [contributor’s agreement](https://support.springsource.com/spring_committer_signup)?

**Comment by adityakishore** [comment]
Hi Eric,
Thanks for taking a look at the PR.
I did sign the ICLA yesterday sometime after sending the pull request.

**Comment by ericbottard** [comment]
Merged as bea8d3f.
Thanks again for your contribution!

**Pull request closed without merging**
